# Generated by Django 5.0.6 on 2024-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("score", models.IntegerField(blank=True, default=0, null=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
