# Generated by Django 5.0.6 on 2024-07-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_blogpost_numscore"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="numScore",
            new_name="numRate",
        ),
        migrations.RenameField(
            model_name="blogpost",
            old_name="score",
            new_name="rate",
        ),
    ]
