# Generated by Django 5.0.6 on 2024-07-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_numscore_blogpost_numrate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="numRate",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="rate",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
