# Generated by Django 5.0.6 on 2024-07-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_blogpost_rate_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="numRate",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="rate",
        ),
    ]
