# Generated by Django 5.0.6 on 2024-07-09 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_blogpost_numrate_remove_blogpost_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="rateTime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
