# Generated by Django 5.0.6 on 2024-07-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rating_ratetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="rateTime",
            new_name="createdTime",
        ),
    ]
