# Generated by Django 5.0.6 on 2024-07-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_ratetime_rating_createdtime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="createdTime",
            new_name="created_at",
        ),
    ]
